### ISSUE TITLE
[Feat] 못한 심화 과제 전부 구현해보자

### ISSUE THREAD

**Issue by mini-min** [DO-SOPT-iOS-Part/LeeMinjae-assignment#11]
# 👀 이슈 (issue)

못한 심화 과제들 전부 구현해보겠습니다. 왜냐구요? 앱잼 전까지 공부할 겸.

# 🚀 to-do

- [x] `2주차 심화과제` DetailVC에서 메인 뷰 리스트 개수만큼 수평 스크롤 가능하도록 구현 + Indicator View 포함
- [ ] `3주차 심화과제` DetailVC 스크롤 시 헤더가 접히도록 구현
- [ ] `3주차 심화과제` 10일간 일기예보 뷰 그라디언트 뷰 커스텀 구현
- [ ] `4주차 심화과제` DetailVC 서버통신 연결 / MainVC 도시 데이터 전달받아 구현할 수 있도록!
- [x] `전체 공통` DetailVC MVC 분리 / Compositional Layout 구성
