### ISSUE TITLE
3주차 iOS 과제 이슈

### ISSUE THREAD

**Issue by mini-min** [DO-SOPT-iOS-Part/LeeMinjae-assignment#5]
# 👀 이슈 (issue)

3주차 과제 입니다~~~~

# 🚀 to-do

- [x] [기본] 메인 뷰 : 지난번에 구현했던 내용들을, TableView와, CollectionView를 이용해서 구현해 봐요!
- [x] [기본] 디테일 뷰 : 지난번에 구현했던 내용들을, TableView와, CollectionView를 이용해서 구현해 봐요!
- [x] [기본] 구현해야 할 내용(10일간의 일기예보 뷰)이 추가되었어요!!
- [ ] [심화] 애플의 날씨앱은, 위로 스크롤 할때 헤더가 접히며 올라가게 되요. 해당부분을 날씨앱과 동일하게 구현해주세요!
- [ ] [심화] 10일간의 일기예보에 있는 그라디언트 뷰를, 이미지를 사용하지 않고 구현해봐요!
- [x] [추가] SearchBar 기능 구현
- [ ] [추가] ToolBar, PageControl 부족한 기능 추가해서 구현
- [x] 기타 자잘한 버그 수정하고, 날씨 앱 클론코딩 기능에 맞게 추가하기
