### ISSUE TITLE
4주차 iOS 과제 이슈

### ISSUE THREAD

**Issue by mini-min** [DO-SOPT-iOS-Part/LeeMinjae-assignment#7]
# 👀 이슈 (issue)

뭐했다고 벌써 4주차 과제인지

# 🚀 to-do

- [x] Open Weather Map API로 서버 붙이자 (MainVC)
- [ ] Open Weather Map API로 서버 붙이자 (DetailVC)
- [ ] 자잘한 챌린지 요소 및 리팩토링 할 수 있음 해볼게요 ^___^
